### ISSUE TITLE
Create shareable database export

### ISSUE THREAD

**Issue by wilson29thid** [29th/personnel-v3#3]
The project team will need a recent sql dump of the production database to develop with locally. Since the production database may contain sensitive or privileged information (e.g. bn hq discussions, some notes), we'll want the export to exclude that. The export should not be shared outside the project team.

Once it's exported, we'll need to [upgrade it to v8.0](https://github.com/29th/personnel-v3#upgrading-the-database-snapshot) unless we do #2 first.

An alternative to this export is to flesh out [fixtures](https://github.com/29th/personnel-v3/tree/master/test/fixtures) to the point that it's a realistic sample database. That would be worthwhile for sure, but not quite as realistic (certainly not in terms of scale).

I think the way to do this is @swomma has a poke around the database, and runs his thoughts by @Wheatles29 for confirmation.

**Comment by swomma** [comment]
LTC @Wheatles29 agrees that only sensitive data is in `notes` table - we can safely export anything with levels "Members Only" and "Public".

Additionally we could omit data from `usertracking` table since it is quite large (~40MB) and not very important - we can just export its structure for compatibility's sake

**Comment by wilson29thid** [comment]
I think this is the command we'll need to do:

```
mysqldump --ignore-table=notes --ignore-table=usertracking personnel_v2 > dump.sql
mysqldump --where="note_access_level <= 'member'" personnel_v2 notes >> dump.sql
mysqldump --where="date >= subdate(current_date, 1)" personnel_v2 usertracking >> dump.sql
```

Of course replacing the `where` clauses with the proper fields/conditions. Note the double `>>` to append rather than replace.

**Comment by wilson29thid** [comment]
I have a copy of the DB extract from the new v8 DB, with the above commands. Had to do `--where="access <= 2"` and `--where="datetime >= '2019-12-06'"` (which is no usertracking records oddly) but otherwise worked. I've shared this with W/O Stray. Anyone else who needs it can ask me.
